[project]
name = "get-weather"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "jcguerrero@correo.iue.edu.co"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests (>=2.32.3,<3.0.0)"
]

[tool.poetry.dependencies]
stats_lib = {path = "../../first_activity/stats_lib", develop = true}
statistics = ">=1.0.3.5" 


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
